### ISSUE TITLE
Wifi Password location?

### ISSUE THREAD

**Issue by saikek** [EpicLPer/Sonoff_GK-200MP2-B_Dump#2]
Hello, were you able to find where wifi password is stored ?

**Comment by onedayfishsale** [comment]
Edit /mnt/mtd/ipc/cfg/wpa_supplicant.conf. Let me know if it works for you (works fine for me); if so it would probably be worth a PR on the README.

**Comment by EpicLPer** [comment]
Closing cause it seems old and already answered :)
