### ISSUE TITLE
Switch off IR LED?

### ISSUE THREAD

**Issue by sixhills** [EpicLPer/Sonoff_GK-200MP2-B_Dump#3]
Thanks for the great work on this.

Just wondered if you've found any way of switching off the IR LED, so the camera can be used after dark, pointing out through a window?

**Comment by EpicLPer** [comment]
Heya! There's a Sonoff Hack for that camera made by someone else here if you want: https://github.com/roleoroleo/sonoff-hack

You can fully control your camera with this and automate it :)
